Charity.Mvc/Controllers/DonationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Charity.Mvc.Models;
using Charity.Mvc.Services.Interfaces;
using Charity.Mvc.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Charity.Mvc.Controllers
{
    public class DonationController : Controller
    {
        private readonly IInstitutionSerwice _instytutionService;
        private readonly ICategoryService _categoryService;
        private readonly IDonationService _donationService;
        private readonly ICategoriesForDonations _categoriesForDonation;

        public DonationController(IInstitutionSerwice instytutionService,
                                ICategoryService categoryService,
                                IDonationService donationService,
                                ICategoriesForDonations categoriesForDonation)
        {
            _instytutionService = instytutionService;
            _categoryService = categoryService;
            _donationService = donationService;
            _categoriesForDonation = categoriesForDonation;
        }

        //public List<CheckBoxModel> ToCheckBox()
        //{
        //    List<CheckBoxModel> chkItem = new List<CheckBoxModel>();
        //    List<Category> CategoryList = _categoryService.GetAll().ToList();

        //    for (int i = 0; i < CategoryList.Count; i++)
        //    {
        //        chkItem.Add(new CheckBoxModel()
        //        {
        //            Id = CategoryList[i].Id,
        //            Name = CategoryList[i].Name,
        //            IsChecked = false
        //        });
        //    }
        //    return chkItem;
        //}
        [HttpGet]
        public IActionResult Donate()
        {
            List<string> ListaKategorii = new List<string>();

            foreach (Institution c in _instytutionService.GetAll())
            {
                ListaKategorii.Add(c.Name);
            }

            DonationViewModel donationViewModel = new DonationViewModel
            {
                DonationQuantity = 1,
                Categories = (List<Category>)_categoryService.GetAll(),
                Institutions = _instytutionService.GetAll(),
                Instytucje = new SelectList(ListaKategorii)
            };

            return View(donationViewModel);
        }

        [HttpPost]
        public IActionResult Donate(DonationViewModel donationModelView)
        {
            var newDonation = new Donation
            {
                Street = donationModelView.DonationStreet,
                Quantity = donationModelView.DonationQuantity,
                City = donationModelView.DonationCity,
                ZipCode = donationModelView.DonationZipCode,
                PickUpDate = donationModelView.DonationPickUpDate,
                PickUpTime = donationModelView.DonationPickUpTime,
                PickUpComment = donationModelView.DonationPickUpComment,
                Institutions = _instytutionService.Get(donationModelView.DonationInstitutionName)
            };

            _donationService.Create(newDonation);

            foreach (Category cat in donationModelView.Categories)
            {
                if (cat.IsChecked)
                {
                    _categoriesForDonation.Create(new CategoriesForDonations
                    {
                        CategoryId = cat.Id,
                        DonationId = newDonation.Id
                    });
                }
            }


            //var x = donationModelView.DonationQuantity;

            //_donationService.Create(new Donation());


            return RedirectToAction("Summary");
        }


        public IActionResult Summary()
        {
            return View();
        }
    }
        
}

Charity.Mvc/Views/Shared/_AboutUsSection.cshtml
<section id="about-us" class="about-us">
    <div class="about-us--text">
        <h2>O nas</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptas vitae animi rem pariatur incidunt libero optio esse quisquam illo omnis.</p>
        <img src="~/images/signature.svg" class="about-us--text-signature" alt="Signature" />
    </div>
    <div class="about-us--image"><img src="~/images/about-us.jpg" alt="People in circle" /></div>
</section>

Charity.Mvc/Views/Shared/_Footer.cshtml
<footer>
    <div id="contact" class="contact">
        <h2>Skontaktuj się z nami</h2>
        <h3>Formularz kontaktowy</h3>
        <form class="form--contact">
            <div class="form-group form-group--50"><input type="text" name="name" placeholder="Imię" /></div>
            <div class="form-group form-group--50"><input type="text" name="surname" placeholder="Nazwisko" /></div>

            <div class="form-group"><textarea name="message" placeholder="Wiadomość" rows="1"></textarea></div>

            <button class="btn" type="submit">Wyślij</button>
        </form>
    </div>
    <div class="bottom-line">
        <span class="bottom-line--copy">Copyright &copy; 2018</span>
        <div class="bottom-line--icons">
            <a href="#" class="btn btn--small"><img src="~/images/icon-facebook.svg" /></a> <a href="#" class="btn btn--small"><img src="~/images/icon-instagram.svg" /></a>
        </div>
    </div>
</footer>

Charity.Mvc/Views/Shared/_Header.cshtml
<header class="header--main-page">
    <nav class="container container--70">
        <ul class="nav--actions">
            <li><a href="" class="btn btn--small btn--without-border">Zaloguj</a></li>
            <li><a href="#" class="btn btn--small btn--highlighted">Załóż konto</a></li>
        </ul>

        <ul>
            <li><a asp-controller="Home" asp-action="Index" class="btn btn--without-border active">Start</a></li>
            <li><a asp-controller="Home" asp-action="Index" asp-fragment="steps" class="btn btn--without-border">O co chodzi?</a></li>
            <li><a asp-controller="Home" asp-action="Index" asp-fragment="about-us" class="btn btn--without-border">O nas</a></li>
            <li><a asp-controller="Home" asp-action="Index" asp-fragment="help" class="btn btn--without-border">Fundacje i organizacje</a></li>
            <li><a asp-controller="Donation" asp-action="Donate" class="btn btn--without-border">Przekaż dary</a></li>
            <li><a asp-controller="Home" asp-action="Index" asp-fragment="contact" class="btn btn--without-border">Kontakt</a></li>
        </ul>
    </nav>

    <div class="slogan container container--90">
        <div class="slogan--item">
            <h1>
                Zacznij pomagać!<br />
                Oddaj niechciane rzeczy w zaufane ręce
            </h1>
        </div>
    </div>
</header>

Charity.Mvc/Views/Shared/_HelpSection.cshtml
@model IList<Charity.Mvc.Models.Institution>


<section id="help" class="help">
    <h2>Komu pomagamy?</h2>

    <!-- SLIDE 1 -->
    <div class="help--slides active" data-id="1">
        <p>
            W naszej bazie znajdziesz listę zweryfikowanych Fundacji, z którymi współpracujemy.
            Możesz sprawdzić czym się zajmują.
        </p>

        <ul class="help--slides-items">
            @{
                var counter = 0;
                foreach (var institution in Model)
                {
                    counter++;

                    if (counter % 2 != 0)
                    {
                        @:<li>
                            <div class="col">
                                <div class="title">Fundacja @institution.Name</div>
                                <div class="subtitle">Cel i misja: @institution.Description</div>
                            </div>

                            if (Model.Count == counter)
                            {<div class="col"></div>}
                    }
                    else
                    {
                        <div class="col">
                            <div class="title">Fundacja @institution.Name</div>
                            <div class="subtitle">Cel i misja: @institution.Description</div>
                        </div>
                        @:</li>
                    }
                }
            }
        </ul>

    </div>

</section>

Charity.Mvc/Views/Shared/_Layout.cshtml
@{
    ViewBag.Title = "Strona główna";
}

<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title - Oddam w dobre ręce</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>

    @Html.Partial("_Header")

    @RenderBody();

    @Html.Partial("_Footer")

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        @*<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>*@
        @*<script src="~/js/Confirm.js"></script>*@
        @*<script>document.getElementById("commentLi").innerText = "test"</script>*@
    </environment>

</body>
</html>

Charity.Mvc/Views/Shared/_StatsSection.cshtml
<section id="stats" class="stats">

    <div class="container container--85">
        <div class="stats--item">
            <em>10</em>
            <h3>Oddanych worków</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius est beatae, quod accusamus illum tempora!</p>
        </div>

        <div class="stats--item">
            <em>5</em>
            <h3>Wspartych organizacji</h3>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laboriosam magnam, sint nihil cupiditate quas quam.</p>
        </div>

    </div>
</section>

Charity.Mvc/Views/Shared/_StepsSection.cshtml
<section id="steps" class="steps">
    <h2>Wystarczą 4 proste kroki</h2>

    <div class="steps--container">
        <div class="steps--item">
            <span class="icon icon--hands"></span>
            <h3>Wybierz rzeczy</h3>
            <p>ubrania, zabawki, sprzęt i inne</p>
        </div>
        <div class="steps--item">
            <span class="icon icon--arrow"></span>
            <h3>Spakuj je</h3>
            <p>skorzystaj z worków na śmieci</p>
        </div>
        <div class="steps--item">
            <span class="icon icon--glasses"></span>
            <h3>Zdecyduj komu chcesz pomóc</h3>
            <p>wybierz zaufane miejsce</p>
        </div>
        <div class="steps--item">
            <span class="icon icon--courier"></span>
            <h3>Zamów kuriera</h3>
            <p>kurier przyjedzie w dogodnym terminie</p>
        </div>
    </div>

    <a href="#" class="btn btn--large">Załóż konto</a>
</section>